### ISSUE TITLE
Date and Time timezone not taken into account

### ISSUE THREAD

**Issue by RABINGG** [marcelkliemannel/intellij-developer-tools-plugin#11]
Whenever trying to convert a date time in my local timezone to milliseconds, the timezone is not considered other than that it converts with timezone as UTC.
![image](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/100079543/e59adbc5-6def-4475-bf41-7d1d3701edf2)
![image](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/100079543/643f3350-1243-4064-9f79-4aa7a00df6d7)

**Comment by marcelkliemannel** [comment]
Thanks for reporting this. Will be fixed in the next release.
