### ISSUE TITLE
Make it possible to resize panes

### ISSUE THREAD

**Issue by paour** [marcelkliemannel/intellij-developer-tools-plugin#2]
<img width="622" alt="SCR-20230605-kwqy" src="https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/90963/8680e5a7-9475-4bfc-adea-d279e41d81d0">

For example in the JWT workbench, the encoded section is very short, and it can't be resized vertically to show the entire string.

Similarly in most of the other tools, though in most cases you seem to have adopted an even split between the panes.

Great collection of tools, btw, thank you!

**Comment by marcelkliemannel** [comment]
The next release will allow to resize the panes of the JWT tool.
