### ISSUE TITLE
Dockable or at least open in a new window?

### ISSUE THREAD

**Issue by Wintaru** [marcelkliemannel/intellij-developer-tools-plugin#23]
Not sure this is possible with the plugin framework for Rider but if possible it would be nice to be able to open this in a dockable pane, or even use the escape button to dismiss the window. I'd love to be able only pull this up when needed (which is possible with the command palette) and then dismiss it when I'm done without having to use my mouse. Having it stuck on top of my rider window until I'm done with it and have to click close to dismiss it is clunky. Thanks! Great tool!

**Comment by marcelkliemannel** [comment]
Hi, the next release will have the tools additionally available through a tool window in the main window (I think this is what you mean by a "dockable pane"?).
