### ISSUE TITLE
Feature request | Add support for ULID generation and introspection

### ISSUE THREAD

**Issue by Ori-Libhaber** [marcelkliemannel/intellij-developer-tools-plugin#26]
- ULID support should at minimum mirror that of UUID.
- I would also recommend adding the option to generate ULID(s) using a user provided epoch timestamp as well as allowing to extract the latter from a user provided ULID value(s).

Much appreciated :)

**Comment by marcelkliemannel** [comment]
Thanks for the suggestion. The next release will include a ULID generator/parser.
