### ISSUE TITLE
Add Unix Time converter

### ISSUE THREAD

**Issue by ArtDark** [marcelkliemannel/intellij-developer-tools-plugin#36]
Please add a converter from Unix Time to human-readable format

**Comment by marcelkliemannel** [comment]
This is already possible with the "Date Time Converter"
<img width="457" alt="Screenshot 2024-03-01 at 08 02 33" src="https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/3964073/80e53a99-8df3-47db-8219-4d311812f47d">
