### ISSUE TITLE
Androd Studio integration

### ISSUE THREAD

**Issue by AngelEduSuri** [marcelkliemannel/intellij-developer-tools-plugin#46]
Hi, firstly thank you so much for this plugin, is very useful and in intellij works fine, but in android studio some tools does not show like dialog bar or tool window. I did try to add manually, but those options have disappeared, is it possible to improve its integration with this IDE too? Thanks.
![Screenshot_20240408_104410](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/77578301/bcb30300-d27b-4163-8a17-93ae743d7bac)
![Screenshot_20240408_110232](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/77578301/d8294fb4-afc3-48ff-b5ab-1751e61a8b53)

**Comment by marcelkliemannel** [comment]
Unfortunately, the latest version of Android Studio is based on the older IntelliJ version 2023.2, and the minimum version of the plugin has long been 2023.3. Therefore, you are missing some updates that could fix these problems. In the latest version 2.4.0 of the plugin, I have lowered the minimum IntelliJ version back to 2023.2. Could you please try this version again?
