### ISSUE TITLE
Expose the individual tools in Goto Anything (double Shift), and/or allow setting keyboard shortcuts

### ISSUE THREAD

**Issue by boris-chervenkov** [marcelkliemannel/intellij-developer-tools-plugin#49]
Activating a tool using the keyboard will be quite useful.

One way of achieving this is to expose the tools as individual actions/commands in the IDE, and allow search from Goto Anything / Shift-Shift functionality of Jetbrains IDEs.

Another way would to be allow assigning a keyboard shortcut to all tools - as of version  2024-04-19 only a limited set of tools are exposed for keyboard shortcut assignment - see screenshot.
![image_2024-04-19_153752079](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/1232068/ea583c08-bfa9-4ecd-9c9d-3472c82bdacf)

This plugin is an AWESOME TOOL - thank you! :)

**Comment by Tanyajackson638** [comment]
```go
#44 #45 #47 #48
```

**Comment by marcelkliemannel** [comment]
Thanks for the suggestion. The next release will contain a keymap extension:
<img width="737" alt="Screenshot 2024-05-20 at 16 34 29" src="https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/3964073/d40f2e56-0a97-4024-9bc4-1c4c76127591">
