### ISSUE TITLE
Feature request: Adding Native2Ascii Functionality

### ISSUE THREAD

**Issue by zfh521** [marcelkliemannel/intellij-developer-tools-plugin#53]
I'm suggesting adding native2ascii functionality to the 'develop tool' repository. This feature is crucial for internationalization efforts, aiding in converting native-encoded files to ASCII for better handling of non-ASCII characters. It would greatly streamline developers' internationalization tasks and enhance the tool's utility.

http://codetoolset.com/convert/nativeascii/index.html
<img width="1342" alt="example" src="https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/7497471/24e0298c-5dd9-463a-b1a1-481ac726c664">

**Comment by marcelkliemannel** [comment]
This feature has been added in the latest release. It is available through the "ASCII Encoding" tool and in the escape/unscape editor action.
