### ISSUE TITLE
Token generator

### ISSUE THREAD

**Issue by K1ethoang** [marcelkliemannel/intellij-developer-tools-plugin#69]
Same as [IT Tools](https://it-tools.tech/token-generator)
![image](https://github.com/user-attachments/assets/861bc94b-0942-4199-bb08-ce25234c3aaf)

**Comment by marcelkliemannel** [comment]
This functionality is already provided by the "Password Generator" tool.

**Comment by K1ethoang** [comment]
> This functionality is already provided by the "Password Generator" tool.

Thanks
