### ISSUE TITLE
Symbols are copied as HTML entities in Password Generator

### ISSUE THREAD

**Issue by narache** [marcelkliemannel/intellij-developer-tools-plugin#70]
When I press the "Copy to Clipboard" button, "&" is copied as "`&amp;`".
Similarly, "<" is copied as "`&lt;`".
It seems to be copied as an HTML entity.

![2024-12-12_094320](https://github.com/user-attachments/assets/400e1b05-4460-4047-a799-df84e1b39ec8)
In the case of the image above, it was copied to the clipboard as shown below.
`-C&lt;R-6*WC+Qg`

There was no problem with "Bulk Generation".

**Comment by marcelkliemannel** [comment]
Thanks for reporting this. This should be fixed in the latest release.
