### ISSUE TITLE
Date time Converter does not save the Individual format

### ISSUE THREAD

**Issue by wanderleydrumond** [marcelkliemannel/intellij-developer-tools-plugin#8]
After set the Individual format, when the screen is closed and when reopened:

- Individual format radio button is checked
- Standard format radio button is unchecked
- Individual text field is disabled
- Standard format text field is enabled
- Output corresponds to Standard foarmat

Before:
![Captura de ecrã 2023-07-28 144745](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/24917547/91de0336-aded-425e-a6df-76f188792e6e)
After:
![Captura de ecrã 2023-07-28 150256](https://github.com/marcelkliemannel/intellij-developer-tools-plugin/assets/24917547/89ae64d7-a9b2-4398-a151-53c0b80c4bff)

I believe it does not affects the usability of the plugin. It was just something that I notice and think it could be improved once that you reunited so many useful tools.

**Comment by marcelkliemannel** [comment]
Hi, thanks for reporting this. Will be fixed in the next release.
